### ISSUE TITLE
How can i get the dataset

### ISSUE THREAD

**Issue by Melonia-H** [manganarofabio/demo_gesture_recog#1]
hi:
I am also studying depth map gesture recognition. How can I get the dataset?

thanks!

**Comment by manganarofabio** [comment]
For everything concerning the dataset please refer to http://imagelab.ing.unimore.it/briareo. If you like the project star the repo, thanks!

**Comment by Melonia-H** [comment]
I cannot send email to stefano.pini@unimore.it .

**Comment by manganarofabio** [comment]
Why not? Is there any problem with the address?

**Comment by Melonia-H** [comment]
Different countries, So  sending failed!

**Comment by manganarofabio** [comment]
I do not dispose of the dataset. The only way to obtain it is through the linked website. Consider using a VPN. Thanks.

**Comment by maohuui** [comment]
https://github.com/manganarofabio/gestures-collector

**Comment by Melonia-H** [comment]
Referring to your code （https://github.com/manganarofabio/gestures-collector）, I plan to collect the data myself by TOF camera(depth / IR /RGB)
Can you get the joints of your hands with the Leap Motion SDK, Can I get the joints of the hands from the depth image through  Deep learning methods?
